/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anita
 */
public class Cargar_Reportes extends javax.swing.JInternalFrame {
    FondoPanel fondo = new FondoPanel();
    DefaultTableModel modeloRepVenta;
    DefaultTableModel modeloRepDet;
    ArrayList<String> ArrayVentas = new ArrayList<>();

    /**
     * Creates new form Cargar_Reportes
     */
    public Cargar_Reportes() {
        this.setContentPane(fondo);
        initComponents();
        modeloRepVenta = (DefaultTableModel) rep_tb_ventas.getModel();
        modeloRepDet = (DefaultTableModel) rep_tb_det.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        rep_tb_ventas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        rep_tb_det = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_reportes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        rep_tb_ventas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rep_tb_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave de venta", "Fecha", "Hora", "Total de la venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rep_tb_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rep_tb_ventasMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(rep_tb_ventas);

        rep_tb_det.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rep_tb_det.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Producto", "Piezas", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(rep_tb_det);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes de Venta");

        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.jpg"))); // NOI18N
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(btn_reportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rep_tb_ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep_tb_ventasMousePressed
        // click en un registro de la tabla de reporte ventas
        int item = rep_tb_ventas.getSelectedRow();
        String clave = ArrayVentas.get(item);
        mostrarDetallesVenta(clave);
    }//GEN-LAST:event_rep_tb_ventasMousePressed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
        cargarReporteVentas();
    }//GEN-LAST:event_btn_reportesActionPerformed
    private void cargarReporteVentas() {
        modeloRepVenta.setRowCount(0);
        ArrayVentas.clear();
        try {
            Conexion db = new Conexion();
            db.conectar();
            String sql = "SELECT clave_ven, fecha, hora, total FROM venta";
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(sql);
            while (db.miResultado.next()) {
                Object[] objVenta = new Object[]{
                    db.miResultado.getString(1),
                    db.miResultado.getString(2),
                    db.miResultado.getString(3),
                    db.miResultado.getFloat(4)
                };
                modeloRepVenta.addRow(objVenta);
                ArrayVentas.add(db.miResultado.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error (Tabla reporte ventas): " + ex.getMessage());
        }
    }

    public void mostrarDetallesVenta(String clave) {
        try {
            Conexion db = new Conexion();
            db.conectar();
            modeloRepDet.setRowCount(0);
            String sql = "SELECT p.id_producto, p.nombre, d.cant_det, d.subtotal FROM "
                    + "producto p, detalle_venta d "
                    + "WHERE p.id_producto=d.id_producto AND "
                    + "d.clave_ven='" + clave + "'";
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(sql);
            while (db.miResultado.next()) {
                Object[] objDet = new Object[]{
                    db.miResultado.getString(1),
                    db.miResultado.getString(2),
                    db.miResultado.getInt(3),
                    db.miResultado.getFloat(4)
                };
                modeloRepDet.addRow(objDet);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error (Tabla reporte detalles): " + ex.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable rep_tb_det;
    private javax.swing.JTable rep_tb_ventas;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo_ven.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
