/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anita
 */
public class Editar_Producto extends javax.swing.JInternalFrame {

    int id;
    Conexion db = new Conexion();
    int clave;
    ArrayList<String> arrMarca = new ArrayList<String>();
    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Editar_Producto
     */
    public Editar_Producto() {
        this.setContentPane(fondo);
        initComponents();
        llenaArr();
        llenaComB();
        llenaCB();
    }

    public void llenaArr() {
        arrMarca.add("Baby Creysi");
        arrMarca.add("Carters");
        arrMarca.add("Gerber");
        arrMarca.add("DC Comics");
        arrMarca.add("Levis");
        arrMarca.add("OshKosh");
        arrMarca.add("Calvin Klein");
        arrMarca.add("Fisher Price");
        arrMarca.add("Disney");
        arrMarca.add("Mon Caramel");
    }

    public void llenaCB() {
        cb_marca.addItem("Elige una marca:");
        for (int i = 0; i < 10; i++) {
            cb_marca.addItem(arrMarca.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_clave_ep = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        tx_clave_ep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_nombre_ep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_cant_ep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_marca = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        tx_precio_ep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_desc_ep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clave:");

        cb_clave_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cb_clave_ep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_clave_epItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clave:");

        tx_clave_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");

        tx_nombre_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");

        tx_cant_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");

        cb_marca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");

        tx_precio_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion:");

        tx_desc_ep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EDITAR PRODUCTO");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(31, 31, 31))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel5)
                                    .addGap(29, 29, 29)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tx_clave_ep, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tx_desc_ep, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tx_precio_ep, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_marca, javax.swing.GroupLayout.Alignment.LEADING, 0, 202, Short.MAX_VALUE)
                                .addComponent(tx_cant_ep, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tx_nombre_ep, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cb_clave_ep, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_clave_ep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_clave_ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_nombre_ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_cant_ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_precio_ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_desc_ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_clave_epItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_clave_epItemStateChanged
        // TODO add your handling code here:
        // nom = String.valueOf(cb_producto.getSelectedItem());
        clave = Integer.valueOf(cb_clave_ep.getSelectedItem().toString());
        Buscar();

    }//GEN-LAST:event_cb_clave_epItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!tx_clave_ep.getText().isEmpty() && !tx_nombre_ep.getText().isEmpty() && !tx_cant_ep.getText().isEmpty()
                && !cb_marca.getSelectedItem().toString().equals("Elige una marca:") && !tx_precio_ep.getText().isEmpty() && !tx_desc_ep.getText().isEmpty()) {
            EditarProducto();
        } else {
            JOptionPane.showMessageDialog(this, "Llenar todos los campos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void llenaComB() {
        try {
            db.conectar();
            String query = "SELECT * FROM producto";
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(query);
            while (db.miResultado.next()) {
                cb_clave_ep.addItem(db.miResultado.getString(1));

            }
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    public void EditarProducto() {
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            Conexion bd = new Conexion();
            bd.conectar();
            String sql = "UPDATE producto SET id_producto=?,nombre=?,piezas=?,marca=?,precio=?,descripcion=? WHERE id_producto=" + id + ";";
            String sqlexis = "UPDATE existencias SET id_producto=?,exis_prod=? WHERE id_producto = " + id + ";";

            PreparedStatement sentencia = bd.miConexion.prepareStatement(sql);

            sentencia.setInt(1, Integer.parseInt(tx_clave_ep.getText()));
            //System.out.println("codigo de barras "+Integer.parseInt(rp_tx_clave.getText()));
            sentencia.setString(2, tx_nombre_ep.getText());
            sentencia.setInt(3, Integer.parseInt(tx_cant_ep.getText()));
            sentencia.setString(4, cb_marca.getSelectedItem().toString());
            //System.out.println(" combo "+rp_tx_marca.getSelectedItem().toString());
            sentencia.setFloat(5, Float.parseFloat(tx_precio_ep.getText()));
            sentencia.setString(6, tx_desc_ep.getText());
            sentencia.execute();
            sentencia.close();

            PreparedStatement sentenciaExis = bd.miConexion.prepareStatement(sqlexis);
            sentenciaExis.setString(1, tx_clave_ep.getText());
            sentenciaExis.setInt(2, Integer.parseInt(tx_cant_ep.getText()));
            sentenciaExis.execute();
            sentenciaExis.close();
            JOptionPane.showMessageDialog(this, "DATOS ACTUALIZADOS");
            limpiar();

        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

    public void Buscar() {
        try {
            limpiar();
            Conexion db = new Conexion();
            db.conectar();
            //CReamos la coonsulta
            String query = "SELECT * FROM producto WHERE id_producto='" + clave + "';";
            //Crear comando que ejecta la consulta la sentencia y ejecutarla
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(query);
            //Imprimir cada uno de los registros de la tabla
            String linea = "";

            while (db.miResultado.next()) {

                tx_clave_ep.setText(String.valueOf(db.miResultado.getInt(1)));
                tx_nombre_ep.setText(db.miResultado.getString(2));
                tx_cant_ep.setText(String.valueOf(db.miResultado.getInt(3)));
                cb_marca.setSelectedItem(String.valueOf(db.miResultado.getString(4)));
                tx_precio_ep.setText(String.valueOf(db.miResultado.getFloat(5)));
                tx_desc_ep.setText(db.miResultado.getString(6));

                id = Integer.parseInt(tx_clave_ep.getText());
            }

        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }

    }

    public void limpiar() {
        tx_clave_ep.setText("");
        tx_nombre_ep.setText("");
        tx_cant_ep.setText("");
        tx_precio_ep.setText("");
        tx_desc_ep.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_clave_ep;
    private javax.swing.JComboBox<String> cb_marca;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tx_cant_ep;
    private javax.swing.JTextField tx_clave_ep;
    private javax.swing.JTextField tx_desc_ep;
    private javax.swing.JTextField tx_nombre_ep;
    private javax.swing.JTextField tx_precio_ep;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo_ventanas.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
