package Tienda;

/**
 * @author Jose Rodolfo Vazquez
 * Fecha: 18/02/2018
 */

import java.awt.*;
import javax.swing.*;

public class Fondo extends javax.swing.JPanel {
    
    public ImageIcon fondo;

    /** Creates new form Fondo */
    public Fondo() {
        initComponents();
    }
    
    public Fondo(int ancho, int alto) {
        this.setSize(ancho,alto);
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        Dimension tam=getSize();
        fondo=new ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"));
        g.drawImage(fondo.getImage(), 0, 0, tam.width,tam.height,null);
        setOpaque(false);        
        super.paintComponent(g);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
