/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anita
 */
public class Mostrar_Inventario extends javax.swing.JInternalFrame {

    FondoPanel fondo = new FondoPanel();
    JTextField id = new JTextField();
    DefaultTableModel modelo;

    /**
     * Creates new form Mostrar_Inventario
     */
    public Mostrar_Inventario() {
        this.setContentPane(fondo);
        initComponents();
        modelo = (DefaultTableModel) tb_productos.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx_nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        inv_btn_MosInv = new javax.swing.JButton();
        inv_btn_buscar_nombre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tx_marca = new javax.swing.JTextField();
        inv_btn_buscar_marca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca:");

        tx_nombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tx_nombre.setOpaque(false);
        tx_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_nombreActionPerformed(evt);
            }
        });

        tb_productos.setAutoCreateRowSorter(true);
        tb_productos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tb_productos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Cantidad", "Marca", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_productos);

        inv_btn_MosInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.jpg"))); // NOI18N
        inv_btn_MosInv.setPreferredSize(new java.awt.Dimension(170, 58));
        inv_btn_MosInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_btn_MosInvActionPerformed(evt);
            }
        });

        inv_btn_buscar_nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_buscar.jpg"))); // NOI18N
        inv_btn_buscar_nombre.setPreferredSize(new java.awt.Dimension(170, 58));
        inv_btn_buscar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_btn_buscar_nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del producto");

        tx_marca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tx_marca.setOpaque(false);
        tx_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_marcaActionPerformed(evt);
            }
        });

        inv_btn_buscar_marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_buscar.jpg"))); // NOI18N
        inv_btn_buscar_marca.setPreferredSize(new java.awt.Dimension(170, 58));
        inv_btn_buscar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_btn_buscar_marcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inv_btn_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inv_btn_MosInv, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inv_btn_buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel2)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(inv_btn_MosInv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inv_btn_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inv_btn_buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_nombreActionPerformed

    private void inv_btn_buscar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_btn_buscar_nombreActionPerformed
        if (!tx_nombre.getText().isEmpty()) {
            limpia();
            BuscarNombre();
        }
    }//GEN-LAST:event_inv_btn_buscar_nombreActionPerformed

    private void inv_btn_MosInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_btn_MosInvActionPerformed
        // TODO add your handling code here:
        Inventario();
    }//GEN-LAST:event_inv_btn_MosInvActionPerformed

    private void tb_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_productosMouseClicked
        // TODO add your handling code here:
        int sel = tb_productos.rowAtPoint(evt.getPoint());
        id.setText(String.valueOf(tb_productos.getValueAt(sel, 0)));
    }//GEN-LAST:event_tb_productosMouseClicked

    private void tx_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_marcaActionPerformed

    private void inv_btn_buscar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_btn_buscar_marcaActionPerformed
        // TODO add your handling code here:
        if (!tx_marca.getText().isEmpty()) {
            limpia();
            BuscarMarca();
        }
    }//GEN-LAST:event_inv_btn_buscar_marcaActionPerformed
    public void BuscarNombre() {
        try {
            limpia();
            Conexion db = new Conexion();
            db.conectar();
            //CReamos la coonsulta
            String query = "SELECT * FROM producto WHERE nombre='" + tx_nombre.getText() + "';";
            //Crear comando que ejecta la consulta la centencia y ejecutarla
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(query);
            //Imprimir cada uno de los registros de la tabla
            String linea = "";

            while (db.miResultado.next()) {
                if (db.miResultado.getString(2).equalsIgnoreCase(tx_nombre.getText())) {

                    modelo.addRow(new Object[]{db.miResultado.getInt(1), db.miResultado.getString(2), db.miResultado.getInt(3),
                        db.miResultado.getString(4), db.miResultado.getFloat(5)});
                }
            }
            tb_productos.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }
    public void BuscarMarca() {
        try {
            limpia();
            Conexion db = new Conexion();
            db.conectar();
            //CReamos la coonsulta
            String query = "SELECT * FROM producto WHERE marca='" + tx_marca.getText() + "';";
            //Crear comando que ejecta la consulta la centencia y ejecutarla
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(query);
            //Imprimir cada uno de los registros de la tabla
            String linea = "";

            while (db.miResultado.next()) {
                if (db.miResultado.getString(4).equalsIgnoreCase(tx_marca.getText())) {

                    modelo.addRow(new Object[]{db.miResultado.getInt(1), db.miResultado.getString(2), db.miResultado.getInt(3),
                        db.miResultado.getString(4), db.miResultado.getFloat(5)});
                }
            }
            tb_productos.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }
    public void Inventario() {
        try {
            limpia();
            Conexion db = new Conexion();
            db.conectar();
            //CReamos la coonsulta
            String query = "SELECT p.id_producto, p.nombre, e.exis_prod, p.marca, p.precio"
                    + " FROM producto p, existencias e "
                    + "WHERE p.id_producto = e.id_producto";
            //Crear comando que ejecta la consulta la centencia y ejecutarla
            db.miSentencia = db.miConexion.createStatement();
            db.miResultado = db.miSentencia.executeQuery(query);
            //Imprimir cada uno de los registros de la tabla
            String linea = "";
            while (db.miResultado.next()) {

                modelo.addRow(new Object[]{db.miResultado.getInt(1), db.miResultado.getString(2), db.miResultado.getInt(3),
                    db.miResultado.getString(4), db.miResultado.getFloat(5)});

            }
            tb_productos.setModel(modelo);
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }

    }

    private void limpia() {
        for (int i = 0; i < tb_productos.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inv_btn_MosInv;
    private javax.swing.JButton inv_btn_buscar_marca;
    private javax.swing.JButton inv_btn_buscar_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_productos;
    private javax.swing.JTextField tx_marca;
    private javax.swing.JTextField tx_nombre;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo_ven.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
